# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mhyt import yt_download


class Ui_youtube(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(601, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.botao_download = QtWidgets.QPushButton(self.centralwidget)
        self.botao_download.setGeometry(QtCore.QRect(420, 250, 141, 41))
        self.botao_download.setStyleSheet("color: rgb(255, 85, 0);\n"
                                          "font: 87 8pt \"Segoe UI Black\";")
        self.botao_download.setObjectName("botao_download")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 0, 391, 31))
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(90, 240, 51, 41))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_2.raise_()
        self.radioButton.raise_()
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 180, 601, 20))
        self.label_4.setObjectName("label_4")
        self.envio_link = QtWidgets.QLineEdit(self.centralwidget)
        self.envio_link.setGeometry(QtCore.QRect(110, 100, 381, 20))
        self.envio_link.setObjectName("envio_link")
        self.envio_arq = QtWidgets.QLineEdit(self.centralwidget)
        self.envio_arq.setGeometry(QtCore.QRect(110, 200, 381, 20))
        self.envio_arq.setObjectName("envio_arq")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 80, 601, 20))
        self.label_2.setObjectName("label_2")
        self.botao_download.raise_()
        self.label.raise_()
        self.envio_link.raise_()
        self.envio_arq.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 601, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Download Youtube"))
        self.botao_download.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">BAIXAR VIDEO</span></p></body></html>"))
        self.botao_download.setText(_translate("MainWindow", "BAIXAR VIDEO"))
        self.label.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#000000;\">DOWNLOAD MP3/MP4 DO YOUTUBE</span></p></body></html>"))
        self.radioButton.setText(_translate("MainWindow", "MP3"))
        self.radioButton_2.setText(_translate("MainWindow", "MP4"))
        self.label_4.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">INSIRA O NOME DO ARQUIVO</span></p></body></html>"))
        self.envio_link.setPlaceholderText(
            _translate("MainWindow", "URL DO VIDEO"))
        self.envio_arq.setPlaceholderText(
            _translate("MainWindow", "NOME DO ARQUIVO"))
        self.label_2.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">INSIRA O LINK DO VIDEO</span></p></body></html>"))

        self.botao_download.clicked.connect(self.download)

    def download(self):
        if self.radioButton_2.isChecked() == True:
            url = self.envio_link.text()
            titulo = self.envio_arq.text()
            titulo_mp4 = titulo + '.mp4'
            yt_download(url, titulo_mp4)
        elif self.radioButton.isChecked() == True:
            try:
                url = self.envio_link.text()
                titulo = self.envio_arq.text()
                titulo_mp3 = titulo + '.mp3'
                yt_download(url, titulo_mp3, ismusic=True, codec='mp3')
            except:
                pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_youtube()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
